"use client";

export default function DraftDisclaimer() {
  return (
    <div
      role="note"
      className="border-t border-[#ecad0a]/30 bg-[#ecad0a]/5 px-6 py-2.5 shrink-0"
    >
      <p className="text-xs font-sans text-[#032147]/70 text-center max-w-screen-xl mx-auto">
        <span className="font-semibold">Disclaimer:</span>{" "}
        Documents generated by AI are drafts for reference only and do not constitute legal advice.
        Please consult a qualified attorney before signing.
      </p>
    </div>
  );
}
